version: '3.8'

services:
  app:
    container_name: planit_app
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    volumes:
      - './app:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URL
    stdin_open: true

  api:
    container_name: planit_api
    build: ./api
    volumes:
      - './api:/api'
    depends_on:
      - postgres
    restart: "always"
    environment:
      - API_PORT
      - ENVIRONMENT
      - FLASK_ENV
      - FLASK_DEBUG
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY

  postgres:
    container_name: planit_postgres
    image: postgres:14.0
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - planit-postgres-data:/var/lib/postgresql/data

volumes:
  planit-postgres-data:
    name: planit-postgres-data