version: '3.8'

services:
  app:
    container_name: planit_app
    build: ./app
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  api:
    container_name: planit_api
    build: ./api
    volumes:
      - './api:/api'
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
