name: PlanIt Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  run_tests_on_pull_request:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: docker-compose -f docker-compose.yml up -d --build
      - name: Lint API
        run: |
          docker exec -t planit_api python -m flake8 --ignore F401,E402,E501,W503 ./api
          docker exec -t planit_api python -m black --check ./api
      - name: Lint APP
        run: |
          docker exec -t planit_app npm run lint
          docker exec -t planit_app npm run prettier-check
      - name: Test API
        run: |
          docker exec -i planit_api python -m pytest ./api -W ignore::DeprecationWarning